### PR TITLE
Open id connect

### LINKED ISSUE #112: OpenID Connect (OIDC) support
I would like to add OpenID Connect (OIDC) support in Titra, but I just want to ask first what you guys thinks about it?

Because I can see that you are selling LDAP support, and I do not want to work against your business model.

Is this something you would be interested in?

### PR DESCRIPTION
**Pull request by AndreasBomholtz**
Added support for OpenID Connect.

This fixed #112

### CODE REVIEW

**Comment by faburem** [comment]
Not directly related to this PR, but I saw you forked the accounts-oidc package:
- do you think you can remove the underscore dependency of the packages and move the code to modern ecmascript?
- are both of these oauth dependencies needed? (might be the case, just curious because it looks weird) 
image

We are trying to limit the amount of dependencies we are pulling in to keep the bundle size small.

**Comment by AndreasBomholtz** [comment]
@faburem Yes I will look into updating the packages. I just updated the dependices to make it work.

**Comment by AndreasBomholtz** [comment]
@faburem I was thinking maybe just merging the oidc package into titra. What do you think about that?

**Comment by faburem** [comment]
I think that is a pretty good idea. That way we could easily use dynamic imports for the functionality only if it is activated for an titra instance. Maybe you can provide me write access on your PR so we can collaborate on the changes together? Also sorry for the delayed feedback, we are currently busy working on customer projects but I plan to spend more time on titra next week!

**Comment by AndreasBomholtz** [comment]
Yes that sounds like a great idea. But I can't figure out how to give you write access to this PR. According to the guides there should be a checkbox to allow you access, but I can't see it.

**Comment by AndreasBomholtz** [comment]
@faburem Can you give some feedback regarding the dynamic import?

And I found out that the _OAuth_ is used for registering the handlers, and _OAuth2_ is the OAuth 2 protocol.

**Comment by faburem** [comment]
sure! So what I imagine is that we move everything out of the packages and instead create a helper library in the utils/ folder. I don't see a need to separate this especially in two packages if we know the exact requirements for titra. The main reason this is handled in a package now is that code has to be added to the server and client (startup). The only generic way to achieve this is through Meteor packages, however in our situation we can control the server and client startup code so I suggest to add everything that the packages are doing right now related to startup (extending Meteor Accounts functionality, ...) directly in our client/server startup scripts and wrap it in an if statement depending on the new globalsetting for OIDC. In addition to that, we can also utilise dynamic imports ```import('/imports/utils/oidc.js').then((OIDCLibExport)=>{...}) ``` to only import the OIDC library code when the globalsetting is set to true. Maybe it will make sense to separate this in two utils - one for the client and one for the server. I think this would also make the oauth dependencies dynamic imports automatically if we only import them in the OIDC library utility scripts.

**Comment by faburem** [comment]
Outstanding work! Are you still working on the PR or do you consider it ready to merge?

**Comment by AndreasBomholtz** [comment]
Yes I think that it is ready for review 😉

**Review by faburem — APPROVED** [review]

**Pull request merged**
